"""modifying the db so that users can upload mulitple images to each recipe

Revision ID: 240d634ec47b
Revises: 60daada52a49
Create Date: 2023-05-05 13:33:00.651133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240d634ec47b'
down_revision = '60daada52a49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    op.drop_table('recipe_images')
    # ### end Alembic commands ###
