"""add user id as foreign key to Recipe table

Revision ID: 79493fb09910
Revises: 1157531d8a71
Create Date: 2023-03-11 17:53:03.867956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79493fb09910'
down_revision = '1157531d8a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
