"""add date_added coloumn to recipes

Revision ID: 80536674c51f
Revises: 79493fb09910
Create Date: 2023-03-11 18:21:16.266269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80536674c51f'
down_revision = '79493fb09910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('date_added')

    # ### end Alembic commands ###
