"""attempting to normalise part of the Recipe table by seperating ingridients from recipe

Revision ID: cf87f78462b3
Revises: 80536674c51f
Create Date: 2023-03-12 13:21:14.955226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf87f78462b3'
down_revision = '80536674c51f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_ingridients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingridient', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=255), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('ingridients')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingridients', mysql.TEXT(), nullable=False))

    op.drop_table('recipe_ingridients')
    # ### end Alembic commands ###
